version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - restore_cache:
        name: Restore yarn package cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
        name: save yarn package cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
      - run: yarn test
  build:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn build
      - add_ssh_keys:
          fingerprints:
            - "4b:a6:e6:18:87:9f:ef:bf:8d:2d:56:fa:cc:f4:1b:b1"
      - run: yarn publish:gh-pages
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
        requires:
          - test
