version: 2
jobs:
  test:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  build:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn publish:gh-pages
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
